import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { app } from '../firebaseConfig'
import { useEffect } from 'react'
import { getAuth, GoogleAuthProvider, signInWithPopup } from 'firebase/auth'
import { useRouter } from 'next/router'


function Register(){
    const auth = getAuth()
    const router = useRouter()
    const googleProvider = new GoogleAuthProvider()




    const signUpWithGoogle = () => {
        signInWithPopup(auth, googleProvider)     
        .then((response) => {
            sessionStorage.setItem('Token', response.user.accessToken)
            sessionStorage.setItem('userToken', response.user.email)
            sessionStorage.setItem('userName', response.user.displayName)
            sessionStorage.setItem('userPhoto', response.user.photoURL)
            //console.log(response.user)
            router.push('/home')

        })   
    }

    useEffect(() => {
        let token = sessionStorage.getItem('Token')
        if (token){
            router.push('/home')
        }
    }, [])


    return (
        <div className={styles.container}>
                  <Head>
        <title>Upgrade your mental health and productivity - Prodest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://logos.thefunnblog.repl.co/favicon.ico" />
      </Head>
            <div>
               

            <div className='body'>
  <div className="fixed z-50 w-full">
    <header className="bg-blur z-50 bg-white bg-opacity-5 text-gray-600">
      <div className="container mx-auto flex flex-col flex-wrap items-center p-5 md:flex-row">
        <a href="#" className="title-font colDark mb-4 flex items-center font-medium md:mb-0">
          <img className="logo" src="https://logos.thefunnblog.repl.co/prodest.svg" alt="prodest logo" />
        </a>
        <nav className="flex flex-wrap items-center justify-center font-medium md:ml-auto">
          <a href="#features" className="colDark mr-5">Features</a>
          <a href="#research" className="colDark mr-5">Research</a>
        </nav>
        <button onClick={signUpWithGoogle} className="bgDark mt-4 inline-flex items-center rounded-xl py-2.5 px-7 text-base font-medium text-white duration-100 focus:outline-none md:mt-0">Login With Google</button>
      </div>
    </header>
  </div>
  <div className="bgGrad  flex w-full justify-center overflow-hidden py-8 pt-48 md:pt-20">
    <img alt="background image" src="https://logos.thefunnblog.repl.co/bgimg2.svg" className="w-full opacity-30 z-0 h-full top-0 left-0 absolute" />
    <div className="z-40">
      <div className="flex justify-center">
        <div className="colDark mt-10 w-5/6 text-center text-5xl font-black sm:text-6xl md:w-4/6 md:text-7xl">
          <div className="black font-2 capitalize">the website to take control of your <span className="grad-text">mental health and productivity</span></div>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="col1 mt-3 w-5/6 text-center text-xl sm:w-4/6 md:w-2/6">A scientifically backed web app that let&apos;s you take control of your mental health and productivity with use of various practices such as meditation, excersize, gratitude, and more.</div>
      </div>
      <div className="mt-5 mb-7 flex w-full justify-center md:mt-7">
        <div className="flex flex-col sm:flex-row">
          <div className="button1 mr-1 transform flex-row-reverse items-center rounded-xl py-4 px-5 font-semibold text-white duration-100 hover:-translate-y-1">
            <button onClick={signUpWithGoogle} className="inline-flex items-center font-medium outline-none focus:outline-none">
              Login With Google
              <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="ml-2 mt-0.5 h-4 w-4" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7" />
              </svg>
            </button>
          </div>
          <div className="colDark mt-5 mr-1 transform flex-row-reverse items-center rounded-xl py-4 px-5 font-semibold text-white duration-100 hover:-translate-y-1 sm:ml-5 sm:mt-0">
            <a href="#features" className="inline-flex items-center">
              Features
              <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="ml-2 mt-0.5 h-4 w-4" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7" />
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div className="img-bg mt-16 flex w-full justify-center pb-12 sm:mt-20">
        <img className="img rounded-2xl" src="https://logos.thefunnblog.repl.co/heroimgmac2.png" alt="hero image example" />
      </div>
    </div>
  </div>
  <div className="lg:px-40">
    <div className="container mx-auto flex flex-col items-center px-5 py-20 md:flex-row">
      <div className="flex flex-col text-center md:mb-0 md:w-5/6 md:items-start md:pr-16 md:text-left lg:flex-grow lg:pr-20">
        <h1 className="colDark mb-4 text-4xl font-extrabold capitalize sm:text-5xl md:text-6xl font-2">Built with you in mind.</h1>
        <p className="col1 mb-6 text-xl">Prodest isn&apos;t just a bunch of boxes to fill out, it&apos;s a scientifically backed platform to set short and long term goals, accomplish, and improve your mental health.</p>
      </div>
      <div className="w-5/6 md:w-4/6 lg:w-full lg:max-w-2xl">
        <img className="rounded-2xl" src="https://logos.thefunnblog.repl.co/imgboxes.svg" alt="prodest ux structure" />
      </div>
    </div>
  </div>
  <div id="features" className="bg-col1 lg:px-40">
    <div className="container mx-auto flex flex-col items-center px-5 py-20 md:flex-row">
      <div className="w-5/6 md:w-4/6 lg:w-full lg:max-w-2xl">
        <img className="rounded-2xl" src="https://logos.thefunnblog.repl.co/productivity.svg" alt="productivity example" />
      </div>
      <div className="mt-10 flex flex-col text-center md:mt-0 md:w-5/6 md:items-start md:pl-16 md:text-left lg:flex-grow lg:pl-20">
        <h1 className="colDark mb-4 text-4xl font-extrabold capitalize sm:text-5xl md:text-6xl font-2">Be productive and do your best work.</h1>
        <p className="colDark mb-6 text-xl">No more messy documents or giant todo lists; set long term goals with the todo widget, daily goals and ideas with the today&apos;s big goal widget, and short term goals with the task manager.</p>
      </div>
    </div>
  </div>
  <div className="bg-col2 lg:px-40">
    <div className="container mx-auto flex flex-col items-center px-5 py-20 md:flex-row">
      <div className="flex flex-col text-center md:mb-0 md:w-5/6 md:items-start md:pr-16 md:text-left lg:flex-grow lg:pr-20">
        <h1 className="colDark mb-4 text-4xl font-extrabold capitalize sm:text-5xl md:text-6xl font-2">mental health, the key to finishing your goals. </h1>
        <p className="colDark mb-6 text-xl">Mental health is one of the most important things to master in life. Not only does it make you feel better, it makes it easier to reach your goals and be productive. Prodest uses scientifically backed mental health techniques to accomplish this.</p>
      </div>
      <div className="w-5/6 md:w-4/6 lg:w-full lg:max-w-2xl">
        <img className src="https://logos.thefunnblog.repl.co/mentalhealth.svg" alt="mental health example" />
      </div>
    </div>
  </div>
  <div id="research" className="colDark px-28 pt-40 text-7xl font-black md:px-40 lg:px-56 font-2">So how does one be happy? Well, we did the research.</div>
  <div className="mt-5 flex w-full flex-row flex-wrap justify-center px-0 sm:px-8">
    <div className="features mt-7 ml-4 mr-4 transform rounded-2xl bg-gray-50 px-5 py-9 duration-100 hover:scale-105 sm:mr-7 sm:ml-0">
      <div className="flex w-full justify-center">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-green-200 text-green-900">
          <svg className="h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="colDark mt-3 text-center text-xl font-bold text-opacity-95">Working Out</div>
      </div>
      <div className="col1 mt-0.5 px-10 text-center text-opacity-80">Exercise is scientifically proven to release feel-good hormones and reduce symptoms of depression and anxiety.</div>
    </div>
    <div className="features mt-7 ml-4 mr-4 transform rounded-2xl bg-gray-50 px-5 py-9 duration-100 hover:scale-105 sm:mr-7 sm:ml-0">
      <div className="flex w-full justify-center">
        <div className="purple-text flex h-12 w-12 items-center justify-center rounded-full bg-yellow-200 text-yellow-900">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
          </svg>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="colDark mt-3 text-center text-xl font-bold text-opacity-95">Gratitude</div>
      </div>
      <div className="col1 mt-0.5 px-10 text-center text-opacity-80">Gratitude helps people feel more positive emotions and remember happy past experiences.</div>
    </div>
    <div className="features mt-7 ml-4 mr-4 transform rounded-2xl bg-gray-50 px-5 py-9 duration-100 hover:scale-105 sm:mr-7 sm:ml-0">
      <div className="flex w-full justify-center">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-red-200 text-red-900">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
          </svg>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="colDark mt-3 text-center text-xl font-bold text-opacity-95">Finding A Goal</div>
      </div>
      <div className="col1 mt-0.5 px-10 text-center text-opacity-80">Defining goals and persuing hobbies improves mental health and wellbeing, along with reducing stress.</div>
    </div>
    <div className="features mt-7 ml-4 mr-4 transform rounded-2xl bg-gray-50 px-5 py-9 duration-100 hover:scale-105 sm:mr-7 sm:ml-0">
      <div className="flex w-full justify-center">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-200 text-blue-900">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="colDark mt-3 text-center text-xl font-bold text-opacity-95">Acts of Kindness</div>
      </div>
      <div className="col1 mt-0.5 px-10 text-center text-opacity-80">Prosocial spending (charity or giving aid to others), volunteering, or just random acts of kindness instills people with a sense of happiness</div>
    </div>
    <div className="features mt-7 ml-4 mr-4 transform rounded-2xl bg-gray-50 px-5 py-9 duration-100 hover:scale-105 sm:mr-7 sm:ml-0">
      <div className="flex w-full justify-center">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-purple-200 text-purple-900">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
          </svg>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="colDark mt-3 text-center text-xl font-bold text-opacity-95">Creating Connections</div>
      </div>
      <div className="col1 mt-0.5 px-10 text-center text-opacity-80">Studies have shown that people with one or more close friends and a high level of social integration are proven to be happier and have lower levels of depression, anxiety, and suicidal thoughts.</div>
    </div>
    <div className="features mt-7 ml-4 mr-4 transform rounded-2xl bg-gray-50 px-5 py-9 duration-100 hover:scale-105 sm:mr-7 sm:ml-0">
      <div className="flex w-full justify-center">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-pink-200 text-pink-900">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
          </svg>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="colDark mt-3 text-center text-xl font-bold text-opacity-95">Positive Mindset</div>
      </div>
      <div className="col1 mt-0.5 px-10 text-center text-opacity-80">A positive mindset can be summed down to optimism, gratitude, and general happiness. Optimism has been proven to help people deal with grief, improve the immune system, and even prevent chronic disease.</div>
    </div>
  </div>
  <div className="bgDark mt-40 py-40">
    <div className="col1 px-28 text-7xl font-black md:px-40 lg:px-56 font-2">Improve yourself, your focus, and your productivity, all at the same time.</div>
    <div className="w-full px-10">
      <div className="h-big mt-20 flex w-full flex-row flex-wrap justify-center">
        <div className=" w-1/4 p-3">
          <div className="md:h-72 w-full rounded-2xl bg-white bg-opacity-5 p-5">
            <div className="h-14 rounded-2xl w-14 bg-gradient-to-br from-purple-100 to-purple-500 flex justify-center items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
              </svg>
            </div>
            <div className="col1 text-2xl font-bold pt-4">Secure</div>
            <div className="col1 text-lg opacity-60">Everything is sercurly connected to a database with a unique code only you can access, meaning only you see what you put.</div>
          </div>
        </div>
        <div className=" w-1/4 p-3">
          <div className="md:h-72 w-full rounded-2xl bg-white bg-opacity-5 p-5">
            <div className="h-14 rounded-2xl w-14 bg-gradient-to-br from-yellow-100 to-yellow-500 flex justify-center items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div className="col1 text-2xl font-bold pt-4">Free</div>
            <div className="col1 text-lg opacity-60">Prodest is completely free. While a premium version is being worked on, all base features will be of no cost as good mental health is a value that everyone should have.</div>
          </div>
        </div>
        <div className=" w-1/4 p-3">
          <div className="md:h-72 w-full rounded-2xl bg-white bg-opacity-5 p-5">
            <div className="h-14 rounded-2xl w-14 bg-gradient-to-br from-pink-100 to-pink-500 flex justify-center items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
            </div>
            <div className="col1 text-2xl font-bold pt-4">Connected</div>
            <div className="col1 text-lg opacity-60">Everything you put is connected to your account only, meaning that you can access your data from anywhere and any place. </div>
          </div>
        </div>
        <div className=" w-1/4 p-3">
          <div className="md:h-72 w-full rounded-2xl bg-white bg-opacity-5 p-5">
            <div className="h-14 rounded-2xl w-14 bg-gradient-to-br from-orange-100 to-orange-500 flex justify-center items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
              </svg>
            </div>
            <div className="col1 text-2xl font-bold pt-4">Backed</div>
            <div className="col1 text-lg opacity-60">The idea of Prodest is backed by research done by multiple studies, making sure what you do will, for a fact, increase your mental health.</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div className="colDark px-28 pt-40 pb-32 text-7xl font-black capitalize md:px-40 lg:px-56 ">
    <div className="font-2">level up your life, set goals, and accomplish them. all for free</div>
    <button onClick={signUpWithGoogle} className="bgDark mt-1 inline-flex items-center rounded-xl py-2.5 px-7 text-base font-medium text-white duration-100 focus:outline-none md:mt-0">Login With Google</button>
  </div>
  <footer style={{background: '#F8FAFC'}} className="body-font">
    <div className="container mx-auto flex flex-col items-center px-5 py-5 sm:flex-row">
      <a href="#" className="title-font flex items-center justify-center font-medium text-gray-900 md:justify-start">
        <img src="https://logos.thefunnblog.repl.co/prodest.svg" className="h-8" alt="logo" />
      </a>
      <p className="col1 mt-4 sm:ml-4 sm:mt-0 sm:py-2 sm:pl-2"><span className="pr-6 text-2xl">|</span> © 2022 Prodest</p>
    </div>
  </footer>
</div>

        
            </div>
        </div>
    )
}

export default Register
